services:
  api:
    build: .
    ports:
      - "8004:8004"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:password1234@host.docker.internal:5432/admin_service
      - REDIS_URL=redis://localhost:6379/0
      - AWS_REGION=us-east-1
    volumes:
      - .:/app
    networks:
      - app-network


networks:
  app-network:
