services:
  api:
    build: .
    ports:
      - "8003:8003"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:password1234@host.docker.internal:5432/kyc_service
      - REDIS_URL=redis://localhost:6379/0
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    networks:
      - app-network


networks:
  app-network:
