services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password1234@host.docker.internal:5432/user_service
      - REDIS_URL=redis://localhost:6379/0
      - JWT_SECRET_KEY=your_development_jwt_secret
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
