services:
  api:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:password1234@host.docker.internal:5432/otp_service
      - REDIS_URL=redis://localhost:6379/0
    volumes:
      - .:/app
    networks:
      - app-network


networks:
  app-network:
