version: '3.8'

services:
  api:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/otp_service
      - MSG91_AUTH_KEY=your_msg91_auth_key
      - MSG91_TEMPLATE_ID=your_msg91_template_id
      - JWT_SECRET_KEY=your_development_jwt_secret
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=otp_service
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
